### ISSUE TITLE
Introduce Model (MVC)

### ISSUE THREAD

**Issue by fredck** [ckeditor/ckeditor5-core#10]
Independently of other MVC aspects, the first thing to get developed is the Model class, providing the basics for model data and observables.

**Comment by fredck** [comment]
This issue also includes the implementation of event emitter tools.

**Comment by Reinmar** [comment]
We haven't yet agree how we want to implement the Model. Related discussion - https://github.com/ckeditor/ckeditor5-design/issues/10.

**Comment by Reinmar** [comment]
Another related thread - https://github.com/ckeditor/ckeditor5-design/issues/7.

**Comment by fredck** [comment]
@Reinmar, I understand that you're asking for a resolution around our MVC strategy before proceeding with this. It makes sense, but the reason why this issue has been opened is that we already have a resolution about one thing: we're going to go with MVC.

The "M" part of MVC and the one that touches this issue is pretty clear, easy to understand and "standardized". It is all about providing the API to define data structures (models) and an event system over them (observables). We don't have any intention to go into the "VC" part of MVC and actually this separation is beneficial, because we can be totally focused on the business model for now without thinking about its visual representation.

Later on, during the development of "VC", there is a good chance that "M" will have enhancements. Still its base will be ready.

The last point is that, the sooner "M" is available, the quicker we can move ahead with the development of the business logic, while designing the "VC" part in the meantime.

Finally, we should keep things easier for us in terms of design decisions. Therefore, I'm opting to base our Model implementation on [Backbone's Model](http://documentcloud.github.io/backbone/#Model) (not strictly, but at least in the high level). We don't have to reinvent the wheel.

**Comment by fredck** [comment]
Note that this issue involves the creation of a [Collection](http://documentcloud.github.io/backbone/#Collection) class as well, to have observable lists as part of the model.

**Comment by fredck** [comment]
Depends on #11.
