### ISSUE TITLE
Range iteration tools

### ISSUE THREAD

**Issue by pjasiun** [ckeditor/ckeditor5-core#100]
There are multiple ways one could want to iterate over a range:
 - standard way - get all opening, closing tags and characters,
 - get nodes - return all nodes, but only once, so the same element will not be returned twice for opening and closing tags,
 - get flat - get only top level nodes, for example if one moved something he could be interested in the nodes which changed parent, so the to level nodes, 
 - merge characters - return text per group of sibling characters with the same attributes, in many cases you want to get text and do not want to handle every character separately. 

Note that one may want to get flat & merge character or get nodes & merge characters, but characters on different levels should not be merged.

This could be handled by passing additional parameters to `positionIteration` (which will be renamed to TreeWalker https://github.com/ckeditor/ckeditor5-core/issues/85), but we should avoid making `PositionIteration` too complex. If it became complex code at this stage of development will became unreasonable complex code soon it the future. Alternatively these could be range methods or simple tools.

**Comment by scofalik** [comment]
`Range.getPositions()` was requested -- iterate through all positions of range. It is kind-of a "standard way" described above, but it is impossible to do in `for..of` loop, because `position` is a property of the `PositionIterator`.

**Comment by scofalik** [comment]
`getAllNodes`, `getPositions`, `getTopLevelNodes` and `getMinimalFlatRanges` have been introduced as `Range` methods. Some of them may take `mergeCharacters` flag as a parameter and then return all characters with the same attributes as one `TextNode`. See PR #139.

**Comment by pjasiun** [comment]
With `TreeWalker` options it becomes a very powerful tools. But some changes need to be still added to close this tickets.

First of all `Range.getTopLevelNodes` is very unoptimised. It iterates over all children, and children of these children to simply get to the next sibling. It would be much simpler if `ignoreChildren` would be another option in the `TreeWalker`. The `TreeWalker` would have an additional `if`, but thanks to it not only the code will work much faster, but also we will be able to use any combination of options we need. Now `Range.getTopLevelNodes` calls `getMinimalFlatRanges` and iterate over all of them. User have no simple way to check if one flat range ends and another starts or execute some code every time the flat range changes. This method is also the most useful for flat ranges and it such cases there is no need to call `getMinimalFlatRanges` at all. I think the method should be removed and the option to the `TreeWalker` should be added, so the code would looks like this:
```
const flatRanges = this.getMinimalFlatRanges();
for ( let range of flatRanges ) {
   const node = range.getNodes( { ignoreChildren: true, mergeCharacters: true } );
   // do whatever you need.
}
```
Second, `.getNodes` (`.getAllNodes`) and `getPositions` are limited. It seems to be a basic case that you want to `getNodes`, when you iterate over flat range and ignore children. In fact having both opening and closing tags does not makes sense if you ignore children. I think that `getAllNodes` and `getPositions` should take walker options as a parameter, and only overwrite `boundaries`.

Third, there is no way to get a regular TreeWalker with options, from the range, with options (`ignoreChildren` or `mergeCharacters`). It would be useful to have `getWalker` or `iterate` which returns a `TreeWalker` instance with the given options.

Fours, `getAllNodes` sounds like a bad name for the method which returns less then regular walker (no `ELEMENT_END`), especially then you will be able to set the options to ignore children. I think it could be simple `getNodes`.
