### ISSUE TITLE
Tests folders structure

### ISSUE THREAD

**Issue by pjasiun** [ckeditor/ckeditor5-core#105]
For some dev files we have a separate tests folders, even if it contains only one file, for example `tests/emittermixin` which contains only `emittermixin.js` test file. For other we have folder for the namespace and a file for each tested file, for example `tests/document/document.js`, not `tests/document/document/document.js`.

I prefer the simpler way, so we will have not bazillion of folders in the tests directory and group tests in folders only if there are so many test files that it is messy to keep them together. But if we are splitting our code into small files, each file should not have too many test files.

**Comment by pjasiun** [comment]
So in other words: we should have folder structure in tests similar to folder structure in src.

**Comment by Reinmar** [comment]
> I prefer the simpler way, so we will have not bazillion of folders in the tests directory and group tests in folders only if there are so many test files that it is messy to keep them together.

I prefer starting grouping as soon as you have more than one test file for a single class. And I of course I agree that wrapping single test file in its own directory from the beginning is unnecessary.
