### ISSUE TITLE
Rename Model to Observable

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-core#126]

**Comment by Reinmar** [comment]
And then rename `Observable#set()` to `Observable#defineAttribute()` and make it callable once per attr name (disallow redefining attrs).

I propose a longer name like `defineAttribute()` because many big classes will extend `Observable` and longer method name will have a better chance to avoid conflicts.

Another change that we could do is also exposing observable mixin. I had that problem already that I wanted to add this behavior to some class, not to inherit it.

**Comment by pjasiun** [comment]
Maybe it should be `defineObservableAttr` or `defineObservable`. If there will be `defineAttr` method in one of these "big" classes, you will avoid conflict, but you will have both `defineAttribute` and `defineAttr` what will be still unclear.

**Comment by pjasiun** [comment]
Also I think that `TreeView#Observer` class may be renamed to `TreeView#Listener` to avoid having two base classes with similar names.
