### ISSUE TITLE
Merge batch, batch-base and register

### ISSUE THREAD

**Issue by pjasiun** [ckeditor/ckeditor5-core#129]
These 3 files separation was an awful circular dependencies workaround. Now, with ES6 modules we can merge these 3 files back together.

Also `register` can be exported as a separate function, so one can use:

`import register form batch.js`

If `register` is everything it need.

**Comment by scofalik** [comment]
Really, I don't see a reason exporting `register` as standalone function. I think it's fine to import `Batch` and use `Batch.register( 'deltaName', ... )`.

**Comment by pjasiun** [comment]
I do not see any reason exporting only one think from the `batch.js`. `Batch` could be a default export, but ES6 may have more export, not only the default one.
