### ISSUE TITLE
Remove load__* in build

### ISSUE THREAD

**Issue by pjasiun** [ckeditor/ckeditor5-core#130]
If one build amd, he does not need `load__cjs`, `load__esnext`. They should be removed from the build.

**Comment by Reinmar** [comment]
AFAIR in the `rename()` callback it's enough to reset the name of the file. That stopped it from being saved. On the other hand, if it's not handled in some custom way by `rename()` it may cause some weird issues (unnamed filed flowing through the pipe).

**Comment by Reinmar** [comment]
BTW. It should be reported here: https://github.com/ckeditor/ckeditor5/issues/50
