### ISSUE TITLE
Model: setupBindToBinding retains the chain

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-core#136]
AFAICS (not tested), the chains (`BindChain`) may be retained by the callbacks created by `setupBindToBinding`. This may lead to increased memory consumption.

I propose to pass only the information which is needed to the `setupBindToBinding`.

**Comment by oleq** [comment]
[This is where passing `chain` should be avoided](https://github.com/ckeditor/ckeditor5-core/blob/1ddfd836e18e547905203d9c146bc562c82857bb/src/model.js#L582).
