### ISSUE TITLE
PendingActions#isPending name is illogical

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-core#142]
Is this plugin pending? No, a plugin cannot be pending. This property means that there are some actions that are pending. Am I right that something like `PendingActions#hasPendingActions` would be more reasonable? cc @AnnaTomanek @oleq

**Comment by oleq** [comment]
`#hasAny` or `#areEmpty` would even make more sense IMO.

**Comment by ma2ciek** [comment]
I'd prefer `PendingActionManager#hasPendingActions` or `PendingActionPlugin#hasPendingActions`, as `actions has actions` doesn't sound good to me. Alternatively `PendingActions#haveAny()` / `PendingActions#areEmpty()`

**Comment by Reinmar** [comment]
This needs to be a property because we want it to be observable. `PendingActions#hasAny` sounds good to me too. Less repetition than on `#hasPendingActions`. If no one's objecting, I'll change the name.

**Comment by AnnaTomanek** [comment]
`PendingActions#hasAny` sounds fine to me, too.
