### ISSUE TITLE
"Saving in progress." should be translatable

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-core#143]
Besides, I'm not sure if it's correct. We want to say that the data is being saved. What's the shortest and most clear way to write that?

This message will be displayed e.g. when someone tries to leave the page while the data is being sent to the server.

cc @AnnaTomanek

**Comment by Reinmar** [comment]
No. In fact, it may be absolutely context-less. He/she may not know that the data is being saved when they try to leave the page.

However, I'm having second thoughts about this – it's the job of the developer who integrates the editor with his/her website to somehow indicate what may that message be about.

**Comment by gok9ok** [comment]
You may be right about whose developer who will integrate it, I don't have much feedback on that but if there is going to be a message, I think there should be two messages, I propose: 
- Saving...
- Saved 

or 

- Saving changes...
- Changes saved.

**Comment by Reinmar** [comment]
I went with "Saving changes". And removed period cause a similar text in ckeditor5-upload doesn't end with one anyway.
