### ISSUE TITLE
Model#unbind: unbinding attribute which is not bound throws ambiguous error

### ISSUE THREAD

**Issue by oleq** [ckeditor/ckeditor5-core#153]
```js
A.bind( 'x' ).to( B, 'a' );
A.unbind( 'totallyNotBoundToAnythingOrEvenNotExistingInA' );
```

**Actual**: `TypeError: Cannot read property 'to' of undefined`

**Expected**: A meaningful error.

**Comment by Reinmar** [comment]
Moved to https://github.com/ckeditor/ckeditor5-utils/issues/5
