### ISSUE TITLE
Stop using "el" in property names

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-core#155]
See https://github.com/ckeditor/ckeditor5-design/issues/16#issuecomment-173531358

PS. "elem" is also forbidden ;).

**Comment by oleq** [comment]
TODO/Note: This issue needs explanation.

**Comment by Reinmar** [comment]
I edited the initial issue description.

**Comment by Reinmar** [comment]
It seems that "el" is used only in ui/*. This will make the fix simpler.
