### ISSUE TITLE
DOM utils

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-core#157]
Let's start gathering ideas for what functions we need in our DOM utils library.

I see it as a set of functions, nothing more. No wrapping which we've been doing in CKEditor 4, because I don't think that there that many quirks still with which we need to deal.

Ideas:

* `dom.insertBefore( toInsert, referenceNode )` and `insertAfter()` because this is awful: https://developer.mozilla.org/en-US/docs/Web/API/Node/insertBefore.
* [?] `dom.remove( el )` because native `remove()` is still fresh (not supported in IE11 – although we can consider requiring polyfills for this; perhaps it's a better idea).
* ...

**Comment by oleq** [comment]
As for `dom.remove( el )`, I see nothing wrong with native `Node.removeChild()`.

**Comment by oleq** [comment]
I suppose we'll need `dom.split( el, index )` and `node.wrapWith( node )` in the future.

**Comment by oleq** [comment]
And `node.getAddress()`.

**Comment by Reinmar** [comment]
> As for dom.remove( el ), I see nothing wrong with native Node.removeChild().

```
// Instead:
el.remove();

// You need this:
const parent = el.parentNode;
if ( parent ) {
    parent.removeChild( el );
}
```

**Comment by pjasiun** [comment]
If you are talking about having a wrapper, I am not sure about another laver of abstractions over the DOM. We will have TreeView which will work like a DOM wrapper, and if we will bring another DOM wrapper we will may end up with plenty of duplicated code. On the other hand if the TreeView will use these wrappers, we will have dom -> wrapper -> treeView -> treeModel, what looks like a little over engineered.

We could have some utils which does not wrap elements, but to be honest I am fine with the native API. I agree with @oleq that `Node.removeChild()` is fine and even the `insertBefore` is something you can used to. At the end of the day, we will not use this API a lot (at least in terms of data handling, I am not sure about the UI).

**Comment by Reinmar** [comment]
As for the proposed methods – what I haven't explained is that **I want this topic to contain only methods which we already missed**. Not which we anticipate that we may miss somewhere. For the time being let's just write down ideas here and later on we can build this util and simplify the existing code.

**Comment by pjasiun** [comment]
On the other hand I was already considered that the TreeView elements (Node, Element, Text) may be simple wrapped DOM elements, with the set of useful methods. Everything they need to have, to be used as a TreeView is a `change` event, fired on the element and its parent, so they may be observable. I the other words if the wrapper object have a `change` event we could remove there object and use more generic wrappers instead.

**Comment by Reinmar** [comment]
Two more ideas:

* `dom.text( [ doc, ], text )` - creating text nodes,
* `dom.element( [ doc, ], name[ ,attributes ] )` - creating elements.

Perhaps we could also bind document:

`
const dom = domUtils( editable.document );
const textNode = dom.text( text );
`

**Comment by oleq** [comment]
> dom.element( [ doc, ], name[, attributes, children ] ) - creating elements.

Where 
```js
children = [ 
    [ name [, attributes, children ] ],
    ...
] 
```
or
```js
children = {
    name: {
        attributes: ..., 
        children: ....
    }
    ...
} 
```
?

**Comment by pjasiun** [comment]
In tree model it is an array (or a single item which will be transformed to array), where you can put string to create a text or a child object:
```
dom.element( 'p', { class: 'x' }, [ 'foo', img, 'bar' ] );
dom.element( 'p', { class: 'x' }, [ 'foo', dom.element( 'img' ), 'bar' ] );
dom.element( 'p', { class: 'x' }, 'foo' );
dom.element( 'p', { class: 'x' }, dom.element( 'img' ) );
```

**Comment by Reinmar** [comment]
I've meant real DOM nodes, but accepting some other format would be a possible extension.

**Comment by Reinmar** [comment]
Moved to https://github.com/ckeditor/ckeditor5-utils/issues/6
