### ISSUE TITLE
Model constructor could accept observable to automatically bind 1:1

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-core#158]
```
new Model( someObservable )
```

It could create an instance of model bound to all observable attributes of `someObservable`. We would also need to add `observedAttributes` property or some other (less public?) way of retrieving all attributes. Alternatively we could just use `Object.keys()`.

**Comment by oleq** [comment]
Use cases?

**Comment by Reinmar** [comment]
I've got the editable (or its model) and I want to create view model for its view which will contain or its props.

On the other hand there's nothing bad in doing this:

```
viewModel.bind( 'isEditable', 'isFocused' ).to( this );
```

But if we'll need to do this a lot then a helper would be useful.

**Comment by Reinmar** [comment]
After reconsidering this issue I don't think that there's any problem.
