### ISSUE TITLE
Check performance of the emitter

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-core#199]
The emitter is a base of many super hot fragments of code and is generally used very wide in the application. This means that it will affect the performance significantly so we should keep it simple and fast. Even so far I see that we use there `arguments` and `fn.apply()` and it may turn out that it will be best to remove them changing the API a bit.

I propose that as soon as we'll have a working editor we should run some tests and see if there are some significant issues.

**Comment by pjasiun** [comment]
:+1: May times I was wondering if I can use event or it is better to have a direct list of callbacks (e.g. https://github.com/ckeditor/ckeditor5-core/blob/master/src/treecontroller/mapper.js#L167-L181, https://github.com/ckeditor/ckeditor5-core/blob/master/src/treeview/treeview.js#L98-L100). I would like to see the performance difference between:

```
for ( callback of callbacks ) {
	callback();
}
```
and event.

**Comment by Reinmar** [comment]
Moved to https://github.com/ckeditor/ckeditor5-utils/issues/7
