### ISSUE TITLE
Unify some assertion styles in the tests

### ISSUE THREAD

**Issue by gregpabian** [ckeditor/ckeditor5-core#20]
This topic was already discussed at the very beginning of CKEditor5 implementation, but I still can find some tests using "wrong" syntax.
As we talked [here](https://github.com/ckeditor/ckeditor5/pull/11#discussion_r23288489) we've chosen to use `expect(A)to.equal(B)` over `expect(A)to.equals(B)` that produces a grammatically incorrect sentence. We should review all the existing tests having that in mind.

**Comment by gregpabian** [comment]
I think in some cases we can use a bit different syntax to improve the readability of assertions.
Since Chai introduces a wide variety of language chains, for cases like this:
```js
expect( config ).to.have.property( 'something' ).to.equal( 'anything' );
```
we could write:
```js
expect( config ).to.have.property( 'something' ).that.equals( 'anything' );
```

Even though the result of both assertions will be the same, the latter one reads much better.

**Comment by fredck** [comment]
I totally agree with the `to.equal()` thing.

As for `.to.have.property( 'something' ).that.equals( 'anything' )` is also cool. Let's just take in consideration that the more we introduce different options for writing the more we'll face mistakes. So either we'll be flexible on accepting minor issues or the reviewer will go ahead fixing things on the spot... or we'll have a heavy bureaucracy to have code finally merged.

**Comment by fredck** [comment]
Fixed `to.equals()` with d76681b.

I would like to have a final ok for the `that.equals()` idea before proceeding with it.

**Comment by gregpabian** [comment]
What if we treated those expects like some sort of a comment? Then we would just check them like any other comment - if they make any sense and are grammatically correct, right?

**Comment by fredck** [comment]
Ok, but here we're talking about code and when coding people tend to copy and paste stuff to move things forward faster. So if I see a `to.equal()` assertion two lines above, I'll just do the same because I may not even be aware that it is possible to do `that.equals()`.

**Comment by gregpabian** [comment]
So the question is what do we want to achieve?  A "quick and dirty" copypasta of assertions that will be hard to maintain few months later or well thought and well written test that would be explicit and easy to understand for new developers?

**Comment by fredck** [comment]
> So the question is what do we want to achieve?

A compromise :)

Btw, I'm ok with both ways... just wanted to bring the other side of the coin to the talk... let's give space for others to leave their opinions as well.

**Comment by Reinmar** [comment]
Since this issue was created we changed many of these assertions and added plenty of new ones, more or less following the good practices. I don't think we need a ticket any more. There still may be some ungrammatical assertions, but that will either stay with us forever (this means, no one cares and touches that code) or we'll slowly fix them.
