### ISSUE TITLE
Creating processing pipelines (and other extensions to the EmitterMixin)

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-core#200]
When decoupling the code we often encounter certain types of situations like:

* creating some processing pipeline which can be extended by other components,
* querying for a value or simply acceptance of some fact (like – should the browser take a default action when a button was clicked) when multiple components take a decision.

## CKEditor 4

In CKEditor 4 we tended to use the emitter's capabilities for all these scenarios. This was possible due to the following features of the emitter:

1. Events could be cancelled and then the `fire()` method was returning `false`. Events could also be stopped (next listeners are not called).
2. `fire()` accepted a "data" param which was later available for each listener in `evt.data` and could be changed by them. It was also returned by `fire()` if the event wasn't cancelled.

Additionally, the emitter had other useful features:

1. It accepted listener priorities, so it was possible to do something before or after some other listener, allowing organising a queue of processors and overriding some other listeners. However, you had to know with which priority you need to listen to be called before or after some other listener and when the queue grew with time there were listeners with random priorities spanning from negative to high positive values (-2 to 99999).
2. `on()` was returning an object with a `removeListener()` method allowing for deregistering the listener. This is necessary when the component is destroyed and should stop listening to events it does not want to or cannot handle any more.

## CKEditor 5

I think that in CKEditor 5 we won't need so many pipelines like the v4's `editor#paste`, `editor#toHtml`, etc. I also think that they will be much less complicated, because those algorithms will be split into more composable components. We also don't have a super clear expectations yet, other than what is discussed in https://github.com/ckeditor/ckeditor5-design/issues/124#issuecomment-182392425 (the `checkEnabled()` implementation).

### Extending the Emitter

The current state of the emitter is that it performs a single task only – being the emitter. It allows for registering listeners, it emits events, passes arguments to them, allow stopping events and cleaning listeners (with a handful `stopListening()` simplifying the destruction of components by registering their listeners).

The emitter is a base of many super hot fragments of code (inside the data model, data bindings, UI, etc.) and is generally used very widely in the application. This means that it may  significantly affect the performance so we should keep it simple and fast. Therefore, we'll need to test its performance (#199). We should also think twice before adding more features to it, especially if they can affect its performance (#21).

Hence, it doesn't seem to be the best option to put more features into the emitter, including the ability to be used for more complex processing pipelines. Especially that we cannot predict today all the use cases and features we would like to add.

### Higher Level Expectations

I've been trying to understand what kind of features we are actually trying to add to the emitter. I realised that the processing pipeline can be generalised as `Array#reduce()`. The simple emitter is then the `Array#forEach()` incarnation. We can also expect that a need for other array methods will appear with time. Does the fact that the original methods are all available in a single class means that it's ok to add them to the emitter? Perhaps that's true. However:

* they should be implemented by separate methods (so `fire()` should serve for `forEach()` and some `fireReduce()` (:D) for `reduce()`),
* the listeners are still anonymous so there's no way to better organise their prioritisation.

### Specialised Solution

Building something new for the processing pipeline seems to be a viable solution as well. However, building it from scratch will require a lot of code to not waste some of emitter's features like prioritising listeners, ability to stop the execution or the handy `listenTo()` and `stopListening()`. What if we used the emitter to build such a pipeline?

During an internal discussion we came up with such a solution:

```js
class Pipeline {
	constructor() {
		this._emitter = Object.create( EmitterMixin );

		this._priorities = new Map();
	}

	add( store, processorName, callback, priority ) {
		store.listenTo( this, 'data', ( evt, evtData ) => {
			evtData.data = callback( evtData.data, evt.stop );
		}, priority );

		this._priorities.set( processorName, priority );
	}

	getPriority( processorName ) {
		return this._priorities.get( processorName );
	}

	write( data ) {
		const evtData = { data };

		this.fire( 'data', evtData );

		return evtData.data;
	}
}

// Usage -------------------

class Clipboard {
	constructor() {
		this.dataPipeline = new Pipeline();

		this.editable.on( 'paste', ( evt ) => {
			editor.insertHtml( this.processPastedData( evt.data ) );
		} );
	}

	processPastedData( data ) {
		return this.dataPipeline.write( data );
	}

	destroy() {
		this.dataPipeline = null;
	}
}


class FileUpload extends Feature {
	constructor() {
		const clipboard = editor.features.get( 'clipboard' );

		clipboard.dataPipeline.add( this, 'fileUpload', ( data ) => {
			return data.replace( /foo/, 'bar' );
		} );
	}

	destroy() {
		this.stopListening();
	}
}

```

It implements a specialised class reusing the emitter, its priorities, `listenTo()`, etc. One of the obvious cons is that this API is not a mixin, so it starts to resemble some other PubSub implementations in which you create the event on the emitter class as a property:

```js
this.clicked = new Signal();

this.clicked.fire();
```

On the other hand, what's wrong with that? Especially, that e.g. an async events functionality can be implemented as a mixin extending the `EmitterMixin` (just like `DomEmitterMixin` does).

... so, WDYT?

**Comment by Reinmar** [comment]
BTW. One thing to note is that the Pipeline implementation does not solve https://github.com/ckeditor/ckeditor5-design/issues/124#issuecomment-182392425 very nicely :D.

**Comment by scofalik** [comment]
I like the idea of `Pipeline` in general and am happy that the integration with `EmitterMixin` is so simple. Regarding your doubts about using `Pipeline` in `Command` - it will be fairly easy, actually. `.checkEnabled()` will call `.write()` which will return `undefined` or value returned by one of the callbacks. The only thing to care about is to stop the pipeline execution (or however you call it, we need dictionary :P) if your callback returns `true` or `false`. But that was the case before too, so it's ok.

**Comment by oleq** [comment]
I wonder if it's possible to keep data piping separate from event system, e.g. in model attribute. So my idea is that listeners can be grouped. Grouped listeners are like some sort of transaction, with sub–transactions for each listener in the group (each has a priority). Once the transaction is done, model fires `change` and another group starts processing the output of the previous "transaction". Something like:

```js
class Clipboard {
	constructor() {
		const model = new Model( {
			pastedData: ''
		} );

		this.editable.on( 'paste', ( evt ) => {
			model.pastedData = evt.data;
			editor.insertHtml( model.pastedData );
		} );
	}
}

class FileUpload extends Feature {
	constructor() {
		const clipboard = editor.features.get( 'clipboard' );

		this.listenTo( clipboard.model, 'change:pastedData', [ 'pasteGroup', 1 ], () => {
			// change:pastedData is not fired as long as "pasteGroup" listeners are being processed.
			clipboard.model.pastedData = '...';
		} );
	}

	destroy() {
		this.stopListening();
	}
}

class AnotherFeatureInterestedInPasting extends Feature {
	constructor() {
		const clipboard = editor.features.get( 'clipboard' );

		this.listenTo( clipboard.model, 'change:pastedData', [ 'pasteGroup', 10 ], ( evt ) => {
			// change:pastedData is not fired as long as "pasteGroup" listeners are being processed.
			clipboard.model.pastedData = '...';

			// The processing in "pasteGroup" ends in this listener.
			evt.stop();
		} );
	}

	destroy() {
		this.stopListening();
	}
}

class FeatureWhichWillNotBeAbleToProcessData extends Feature {
	constructor() {
		const clipboard = editor.features.get( 'clipboard' );

		this.listenTo( clipboard.model, 'change:pastedData', [ 'pasteGroup', 20 ], () => {
			// Never executed; stopped at priority 10.
			clipboard.model.pastedData = '...';
		} );
	}

	destroy() {
		this.stopListening();
	}
}
```

I'm curious about pitfalls of such solution.

**Comment by pjasiun** [comment]
At first I liked this separation, but...

What we do on events is many times changing a data structure. They have priorities to do it in some orders. This means they do some kind of pipelining on another structure, but can not modify parameters, pass parameter from one listener to another or return a value. Sounds more like the limitation, then separation.

Also the clipboard is a pretty bad example. The idea of the 'paste' event was to fire it on the `TreeView`. If a clipboard observer is available the `paste` event is fired. If not, it is not fired. It does not mean that there are not features which listen on this event. Now, if the pipeline need to be a separate property, each feature needs to check if it is available.

Also, the idea was that the `paste` is the simple view event, from the `TreeView` point of view. It is fired like `mutation`, `enter` or `selectionChange`. It is hard to tell which of these should be a pipeline, which should be an event. It should be possible to cancel any of these. For some pipelining makes sense, `paste` have a data transfer and some listener may want to overwrite data value with the transformed pdf or a file placeholder. But it depends on features what they want to do with events.

Also, we are thinking about using a single object instead of list of parameters for events, because of the performance (https://github.com/ckeditor/ckeditor5-core/issues/199). Then the difference between events and pipelines will be even smaller. They could have methods to return value (`evt.return( data );`) and they would work fine as a pipeline.

And adding names to the pipeline (`fileUpload`) solves nothing. User needs to check this name, so he can check the priority as well. We could call the priority and export it from the module (`export const FILE_UPLOAD = 5`) and the profit will be the same.

Finally, events are main mechanist to extend CKEditor. Users use them in more ways than we imagine it. I do not think they should have limitations.

**Comment by Reinmar** [comment]
After a F2F talk with @pjasiun I must agree that while separation sounds well, it's forced by the shape of the current emitter mixin. It simply misses features which wouldn't make it slower and more complicated.

Second thought is that we should avoid the need to overuse priorities by splitting events into more granular ones. E.g. in CKEditor 4 we had `editor#toHtml` which was creating a pipeline that during its course pre-processes data, parses it, processes parsed data, filters, adjust for editing, stringifies and post-processes. In CKEditor 5 this situation will be much less likely to happen because the architecture is highly modular.

Anyway, there are couple of improvements that we could do to the emitter:

1. Make the `fire()` return the data passed to it. We'll need to decide whether it should accept data as a single param or, like now, as 0-N params. It's unclear which way it may be more performant – on one hand we have `arguments` and `apply()`. On the other we have creating objects (to group more params) on the fly (more pressure on GC). This unfortunately needs to be tested and it should be tested in real life cases.
2. Allow overriding the data inside the listener. I like the idea of `evt.return( data )` as it does not leave the obscure cases like "if a listener returned `undefined` does it mean that it really returned it or didn't return anything". Also, once we implement async emitter the `evt.return()` would simply become `evt.done()` in this case, so the APIs would be similar. Plus, if we decide to allow passing multiple params to `fire()` we'll be able to do `evt.return( a, b, c );`
3. One more thing that I would clean is the default priority. `10` is an odd value. You start thinking that if `10` is default, then `0` must be the minimum. I think that if `0` is default it will create less confusion.

**Comment by Reinmar** [comment]
Moved to https://github.com/ckeditor/ckeditor5-utils/issues/8
