### ISSUE TITLE
Decouple the View and Template

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-core#201]
The view now does some smelly things like this: https://github.com/ckeditor/ckeditor5-core/pull/198/files#r52621125 just to pass some additional info to the template. We should try to find some more elegant way to render the template, perhaps even without all these intermediate functions.

**Comment by oleq** [comment]
It could be something like:

```js
applyTemplateToElement( element, def ) {
  const tpl = new Template( def );
  tpl.registerListenerAttacher( this.listenerAttacherGetter() );
  tpl.apply( element );
}
```

`View` class wouldn't play with template definition at all in such case (except for model bindings). It would be up to Template class to create a rich definition from `Template#definition` using passed `this.listenerAttacherGetter()`, store it internally and use it.

**Comment by Reinmar** [comment]
Moved to https://github.com/ckeditor/ckeditor5-ui/issues/7
