### ISSUE TITLE
Implement toolbar and first UI components

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-core#209]
In order to implement the toolbar we need some buttons registry. To have buttons registry we need to some buttons. We also need to answer the question whether this registry should be a buttons registry or something more generic.

**Comment by pjasiun** [comment]
What do you mean by something more generic? Some buttons are commands (bold), some UI actions (maximise, about), so we can not have a simple list of abstract commands. Or do you mean some generic UI component which can be a button or dropdown or input? Then it makes a lot of sense.

**Comment by pjasiun** [comment]
In fact it would be nice if they would be a list of UI components with attached controllers, without well defined types. Then we could have helpers to create a button or dropdown, but it could be anything.

**Comment by Reinmar** [comment]
In fact, I started this thread to discuss many related aspects: https://github.com/ckeditor/ckeditor5-design/issues/133

**Comment by Reinmar** [comment]
> What do you mean by something more generic? Some buttons are commands (bold), some UI actions (maximise, about), so we can not have a simple list of abstract commands. Or do you mean some generic UI component which can be a button or dropdown or input? Then it makes a lot of sense.

Yes, that was a question whether we need a registry of certain type of UI components, or e.g. all UI components. The issue in the design repo answers this question.

**Comment by Reinmar** [comment]
I see in ckeditor/ckeditor5-design#133 that the idea of copying the chosen UI lib to `dist/ui/` was accepted, so I'll create a simple ticket for ckeditor5 repo. For now we'll only copy the ui-default lib there, not even carrying about keeping its copy under the original name.

**Comment by Reinmar** [comment]
I pushed https://github.com/ckeditor/ckeditor5/tree/ui with a proper setup. You can check out this branch and run `gulp update` to switch the env to this setup.
