### ISSUE TITLE
Implement simple keystroke handler

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-core#231]
Some requirements:

* features should be able to register their keystrokes
* ctrl==cmd on MacOSX
* it should be possible to redefine keystrokes in the configuration

Questions:

* do we want some neat way for defining keystrokes or we can use numbers like in CKEditor 4 (`CKEDITOR.CTRL + 44`)?

**Comment by Reinmar** [comment]
As for:

> do we want some neat way for defining keystrokes or we can use numbers like in CKEditor 4 (CKEDITOR.CTRL + 44)?

I don't think that we'll be able to implement the same functionality, because we cannot add any constant to `CKEDITOR`. It must be possible to redefine keystrokes in the configuration, so it seems that we'll need a string syntax.

**Comment by Reinmar** [comment]
Seems that the keystroke handler needs to use the tree view observers to pass requirements of #233.

**Comment by Reinmar** [comment]
As for defining keystrokes with a string format, I changed my mind after seeing https://github.com/RobertWHurst/KeyboardJS/blob/master/locales/us.js :D.

But we definitely need CTRL, ALT and SHIFT modifiers and we could also provide letters (see https://github.com/RobertWHurst/KeyboardJS/blob/master/locales/us.js#L112-L118), so I'm thinking about API like:

```js
editor.keystrokeHandler.add( 'ctrl', 'b', 'bold' ); // CTRL+B to bold command

// alternative syntax:
editor.keystrokeHandler.add( [ 'ctrl', 'b' ], 'bold' );
```

This way we'll be able to mix string modifiers with numbers:

```js
editor.keystrokeHandler.add( 'ctrl', 48, 'someCmd' ); // CTRL+0
```

The API would prevent the default action if the command can be executed (it isn't disabled). If you need a different behaviour (e.g. not calling the `preventDefault()`) you would pass a callback:

```js
editor.keystrokeHandler.add( 8, ( evt ) => {
    doSomething();
} );
```

The keystrokes which are bound to commands could be reconfigurable through the editor configuration:

```js
CKEDITOR.create( {
    keystrokes: [
      [ 'ctrl', 'b', null ] // unbind bold from CTRL+B
      [ 'ctrl', 'z', 'bold' ] // bind bold to CTRL+Z
    ]
} );
```

**Comment by fredck** [comment]
> editor.keystrokeHandler.add( 'ctrl', 'b', 'bold' ); // CTRL+B to bold command

+1

**Comment by pjasiun** [comment]
> editor.keystrokeHandler.add( 'ctrl', 'b', 'bold' );

What about `editor.keystrokeHandler.add( 'ctrl+b', 'bold' );`?

**Comment by Reinmar** [comment]
@pjasiun: You couldn't then support key codes?

**Comment by fredck** [comment]
> @pjasiun: You couldn't then support key codes.

+1

**Comment by pjasiun** [comment]
Why not `editor.keystrokeHandler.add( 'ctrl+48', 'bold' );` if you need it? I do not like `'ctrl', 'b', 'bold'`, it is unclear for me where list of keys ends. My first thought was that you handle a `bold` button on some mobile virtual keyboard. Now we can said that the last parameter is always a command name, but what if you will add additional optional parameter?

**Comment by Reinmar** [comment]
Does

```js
editor.keystrokeHandler.add( 'ctrl+4', 'bold' );
```

mean number "4" or a key code 4?

I agree that:

```js
editor.keystrokeHandler.add( 'shift', 'enter', 'enter' );
```

would be unfortunate, but:

1. either we can ignore this, because we won't support 'enter' key anyway (you need to pass a number),
2. we can use the array format.

**Comment by pjasiun** [comment]
> 2. we can use the array format.

Then I am for the array format or mixed string (with `+`) for simple formats, or array for more complex:
```
editor.keystrokeHandler.add( 'ctrl+b', 'bold' );
editor.keystrokeHandler.add( ['ctrl', 'b'], 'bold' );
editor.keystrokeHandler.add( ['ctrl', 48], 'bold' );
```

**Comment by Reinmar** [comment]
Makes sense.

**Comment by Reinmar** [comment]
BTW. I named the method `add()` because initially I wanted to propose `editor.keystrokes`. The class could still be called `KeystrokeHandler`.

**Comment by fredck** [comment]
Hum... the array indeed makes it more readable and .split( '+' ) would in any way return an array. @pjasiun's proposal looks good then. At this point, 'ctrl+1' should mean the "1" key.

**Comment by Reinmar** [comment]
> At this point, 'ctrl+1' should mean the "1" key.

I'm actually thinking about adding few more keys to cover letters, numbers, backspace, delete, enter, space, arrow keys. That should cover >90% of cases.

**Comment by fredck** [comment]
> cover letters, numbers

Just KISS (and as short as possible)... we don't need "one" or "questionmark" :)

**Comment by Reinmar** [comment]
By letters I meant a-z, and 0-9. No magic :P.

**Comment by Reinmar** [comment]
Moved to https://github.com/ckeditor/ckeditor5/issues/115
