### ISSUE TITLE
Async features

### ISSUE THREAD

**Issue by pjasiun** [ckeditor/ckeditor5-core#25]
Some features may not need to be loaded to initialize editor. At the same time, these might be plugins which take some time to load. Think about the external parser which let you paste PDF file, but needs to load an external parsing library. Or about the autocompletion which works with the server side API and needs authorization.

We already let users create such plugins because the `init()` function may return a `Promise`. The problem is then such plugins will extend the time you wait for the editor to be up and ready. Note that such plugins do not need to be loaded to let you see caret blinking in the editor.

This is why I propose to introduce asynchronous features:
```
export default class Autocomplete extends Feature {
	init() {
		const editor = this.editor;
	}

	get async() {
		return true;
	}
}
```

Or:

```
export default class Autocomplete extends Feature {
	asyncInit() {
		const editor = this.editor;
	}
}
```

Of course, it will be a lie, the editor will not be fully ready at the moment when you see it ready, but for many features, it does not matter. At the same time, a user will have a feeling that editor loads very fast. It is a similar kind of lie iPhone do showing you the screenshot of the app when you open it, before the app fully loads, giving you feeling that everything works smoothly.

Note that all plugins which require async plugin need to be async too. I think we should throw an exception if the sync plugin requires async one.

**Comment by pjasiun** [comment]
And that is true that now it is possible to `return true` from the `init` function and load the code asynchronously. But, first, you need to handle it manually, and, second, you can not require such plugin, so the most important feature of the plugins mechanism stop working.

**Comment by fredck** [comment]
Let's supposed that, using your example, the PDF library takes 10 seconds to load and the user pastes a PDF before it. How would your proposal solve the asynchronicity problem?

The only option to do this right is to have the feature integrating with clipboard, so if anything is pasted, the user gets blocked, waiting for my async loading to finish so the pasting gets finally processed. 

To do so, the feature needs to do partial sync work for the integration with clipboard, while it uses flags or whatever other methods to signalize that it is in "waiting mode" for the external script. So it doesn't need to tell the editor core that it is async, but it needs to tell it to itself.

How would the async init be the solution for that? All the above should be done in the usual `init()` method.

And I confirm that `init()` returning a promise solves a specific need: "do NOT create the editor without me". We can consider this a different case.

**Comment by pjasiun** [comment]
First of all, I think that 10 seconds of loading is an edge case. A more likely case is 0.5 second. And this 0.5 second give you a bad/heavy feeling when you need to wait for the editor to be loaded. At the same time, it is very unlikely that you will paste something in that first 0.5 second. 

But if you do, or if, because of some network problem it takes longer, and you paste it before the plugin is loaded the editor will behave in the way as there is no PDF plugin. Most probably your PDF will not be paste. The same way as iPhone do nothing when you press a button on the screenshot you see before the app is ready (sometimes because of a lag). Even if sometimes you get the feeling that something is not working, in general, you have a feeling that apps load very fast.

Sure, that is a very simple mechanism, it can be done better in some plugins which will be synchronous to add warnings or mockups that some async data are not ready. But, I believe, that in many cases such simple mechanism might be good enough. If a user will see the editor immediately when the website loads we gain more, then we loose then someone met unexpected behavior.

**Comment by fredck** [comment]
I can't agree with the above, but in any case, I still don't understand what problem you want to solve, sorry :/

You don't have to return a promise in `init()` in any of your examples. You simply start an async operation inside the usual `init()` method and let it go. You don't have to block the editor initialization.

**Comment by Reinmar** [comment]
Fred wrote exactly what I told you earlier. You have perfect flexibility now and pushing more into the plugins collection isn't required - it's external logic or logic which is your feature's logic.

**Comment by pjasiun** [comment]
Ok, then I'm closing this ticket if you both agree it's useless feature.
