### ISSUE TITLE
Feature: Undo

### ISSUE THREAD

**Issue by scofalik** [ckeditor/ckeditor5-core#250]
Undo manager should be introduced as a Feature for CKE5. Quick overview:

* it should listen to `change` event and register it's own operations/deltas/batches history,
* it should be able to revert and apply the `Batch` from which most recently got updated,
* it should keep a separate stack for undo and redo, so deltas applied by undo'ing won't be then undone, but could be redone,
* it should be ready for "selective undo" feature,
* it should introduce two commands: "undo" and "redo"

I guess that's all?

**Comment by Reinmar** [comment]
See also https://github.com/ckeditor/ckeditor5/issues/100 (please assign this issue to yourself). At least part of the undo manager system should be implemented as a feature. We need to figure out what's pluggable and fully optional and what's the engine part.

**Comment by scofalik** [comment]
Oh, it was my mistake to create this issue in -core repository. I think that the big part of this feature (or even whole) will be eventually put in separate repo.
