### ISSUE TITLE
Introduce the first "creators"

### ISSUE THREAD

**Issue by fredck** [ckeditor/ckeditor5-core#26]
The basics for the following [creators](https://github.com/ckeditor/ckeditor5-design/wiki/Editor-Instances#the-creator) should be introduced:

 * Inline Editor Creator (`ckeditor5-plugin-inlinecreator`)
 * Classic Editor Creator (`ckeditor5-plugin-classiccreator`)

The minimal expected features:

 * Make the minimal necessary DOM manipulation expected by the creator.
 * Load input data from the source element.
 * Initialize the root editable.
 * On destroy:
   * Revert the initial DOM manipulation.
   * Set output data back to the source element.

**Comment by pjasiun** [comment]
Shouldn't them be called:
`ckeditor5-plugin-creatorclassic` and
`ckeditor5-plugin-creatorinline`.

It would be helpful to keep all creator together since github sort project alphabetically. Also see: https://github.com/ckeditor/ckeditor5-design/issues/60.

**Comment by fredck** [comment]
I think that, if we're talking about plugin names, it should be named in a readable way, apart from convenient organization of the code. "Creator Classic" is senseless. If we would ever think about prefixing such plugins, we may think about `ckeditor5-plugin-creator-classic`.

Anyway, there is a good chance that we'll review this and the final name will be `ckeditor5-creator-classic`.

**Comment by Reinmar** [comment]
#47 introduced basic mechanism to load and start creators and couple of other improvements. That's just the beginning – I'll create new tickets for the rest of the job.
