### ISSUE TITLE
Requirements available as properties

### ISSUE THREAD

**Issue by pjasiun** [ckeditor/ckeditor5-core#26]
When you require one plugin from another it is very likely you will want to use it. It would be nice to have it available as a property. This is why I propose following API change.

Instead:

``` js
import Image from './image.js';

export default class ImageCaption extends Feature {
    static get requires() {
        return [ Image ];
    }
    init() {
        this.editor.plugins.get( Image ).getSize();
    }
}
```

Do:

``` js
import Image from './image.js';

export default class ImageCaption extends Feature {
    static get requires() {
        return { 'img': Image };
    }
    init() {
        this.img.getSize();
    }
}
```

**Comment by pjasiun** [comment]
It's especially useful for features which bring some new API. Think about notifications. In CKEditor 4 such features introduce additional API on the `editor` class. It is not very good way, because of creating one big API, and the possibility of conflicts. On the other hand calling `this.editor.plugins.get( Notification ).show();`every time you want to use it (or creating property manually every time) is not very nice.

Thanks to this new API you could do:

```js
import Notification from '../notification/notification.js';

export default class Upload extends Feature {
    static get requires() {
        return { 'notification': Notification };
    }
    init() {
        this.notification.show( 'foo' );
    }
}
```

**Comment by Reinmar** [comment]
We shouldn't expose these instances as public properties of features. First of all, that's not an API of a feature. Second, it'd just be a bit weird. And it'd be even worse if we'd start complicating things by defining them as `_protected`.

But I agree that we could simplify this. I feel that we could make a shortcut like this:

```js
import Notification from '../notification/notification.js';

export default class Upload extends Feature {
    static get requires() {
        return { notification: Notification };
    }
    init() {
        this.require( 'notification' ).show( 'foo' );

        // or like this, so we wouldn't have to return an object from requires()
        this.require( Notification ).show( 'foo' );
    }
}
```

So `this.require()` would be a shortcut to `this.editor.plugins.get( constructor )`.

**Comment by Reinmar** [comment]
Closing due to lack of interest in this now.
