### ISSUE TITLE
Try to find better name for Selection#storeAttribute method

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-core#260]
Followup for #234.

It's been a bit confusing for me that in one place you have `set/get/removeAttribute()` and next to it you have `_storeAttribute()` and the rest. We need to find a more distinguishable name for the "hoist attributes to the block" functionality.

Some ideas:

* `hoistAttribute()`, `removeHoistedAttribute()`,
* `setBlockAttribute()`, `removeBlockAttribute()`,
* `preserveAttribute()`

**Comment by scofalik** [comment]
I think that most developers are unfamiliar with `hoist` word. Additionally, it is connected more to the implementation details than to what the method does. Remember that we are saving selection's attributes for this "position"/"place". For the same reason I have mixed feelings about `setBlockAttribute`. We are not settings that attribute on the block.

`preserveAttribute` seems decent, but really, what's the difference between `preserve` and `store` other than the first is harder to write?

**Comment by Reinmar** [comment]
> preserveAttribute seems decent, but really, what's the difference between preserve and store other than the first is harder to write?

My main issue is that we've got the set of methods for setting the selection attributes and a separate set of methods for the preservation/storing mechanism. This means that we need to make the latter clear, unless it will be totally hidden from the developers.

**Comment by scofalik** [comment]
Right now it is hidden. I mean that was our point, so 3rd party developer never has to use `_storeAttribute` or anything.

**Comment by Reinmar** [comment]
Right... I've missed that previously. Then, I have no other concerns.
