### ISSUE TITLE
TreeView.addObserver should only allow adding one obsever of a kind

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-core#272]
You can have multiple different feature requiring a single observer. We cannot add all possible observers by default, so each of these features should add it itself. This means that a single observer can be added multiple times, but only the first `addObsever()` call should do something.

That's why I was in favour of passing the observer by a class, not instance. This will be the most optimal way.

**Comment by pjasiun** [comment]
The original idea was to make every observer a feature and assign it to the editing view in the `init` method. This way every feature which need this observer adds it as a dependency and it is initialise only once for every editor. But your solution make sense as well.
