### ISSUE TITLE
Move dev utils to src

### ISSUE THREAD

**Issue by pjasiun** [ckeditor/ckeditor5-core#29]
Same as https://github.com/ckeditor/ckeditor5-engine/issues/610, tests editors (https://github.com/ckeditor/ckeditor5-core/tree/master/tests/_utils) should be moved to the src.

**Comment by Reinmar** [comment]
Yy... How would you use the test editors for development? I mean – in what case they'd be useful?

**Comment by pjasiun** [comment]
For the 3rd party plugins development, when you do not compile CKEditor 5 tests (because why should you compile them if you are developing  3rd party plugin?).

**Comment by oskarwrobel** [comment]
The same problem is with [LocaleMock](https://github.com/ckeditor/ckeditor5-utils/blob/0ec1135891dd4754cb9acaa46e8ab95b7862d7b9/tests/_utils/locale-mock.js).

**Comment by Reinmar** [comment]
Closing due to lack of interest in this.
