### ISSUE TITLE
Change ToggleAttributeCommand#_doExecute argument to an object

### ISSUE THREAD

**Issue by maxbarnas** [ckeditor/ckeditor5-core#34]
**Problem:** Cannot provide additional parameters to commands like Bold or Italic. Using object instead of just `forceValue` param will fix that.

As a part of the task, there should be added additional parameters: `batch` for grouping undo steps and `ranges` for specifying ranges to apply command to.

**Comment by Reinmar** [comment]
Can't this be done together with introducing the new params?

**Comment by maxbarnas** [comment]
Can be done :)

**Comment by Reinmar** [comment]
I've just talked about this with @pjasiun and @fredck and they pointed out that we must not pass `ranges` to the command. The command is a combination of a `execute()` (a method) and a state. If we violate the state by overriding the selection (on which the state bases), then we're negating the sense to having commands.

So, please revert that part of the change, @maxbarnas.

PS. The right way to implement the autoformatter will be to change the selection for a moment. Then, the state of the command will be updated and we'll know what the autoformatter should/can do.
