### ISSUE TITLE
Operation builder

### ISSUE THREAD

**Issue by pjasiun** [ckeditor/ckeditor5-core#35]
It should be possible to bold part of the document using simple command in JavaScript console:
```
var builder = new Builder( document );
builder.addAttribute( range, bold );
builder.modification.render();
```

To do so, Builder and Modification classes should be created. Modification is a set of transactions with additional information about changed nodes.

**Comment by pjasiun** [comment]
The discussion about the names of these classes is moved here: https://github.com/ckeditor/ckeditor5-design/issues/68

**Comment by fredck** [comment]
To make the concept public, can you explain why we need a builder and `render()` instead of having each transaction rendered automatically?

**Comment by pjasiun** [comment]
### Why do we need `render()`?
The simply answer is: because of the performance.

In fact not all changes need to be rendered. The best example is typing. When user input a letter in the editor (a.k.a. dirty DOM in this case) that letter is already there. We get it using mutation observer and put into document model. There is no need to render it, because it already is in the dirty DOM. In fact rendering would not be that simple as it may seems to be in this case, because we would need to find the text node which changed (what is not trivial, because text node does not have ids in the DOM) and then compare whole text node (note that it is the document model text node, so the part of the document between two block elements, containing all inline styles) to notice that nothing changed.

But this was only one example. Another might be replacing one text node with another. Because text node do not have id in the DOM there can not be 2 text nodes one next to another. If we add a text node and then remove the second one, both of them will be removed. We could add the second text node again, this is what happens in the prototype, or change the order of these operations (but we would have to change the behavior of the `diff` function to handle this), but the simplest and most proper solution seems to be render the change after it is done.

### Why we need `Builder`?
This's a simpler question. Because we are lazy and do not want to write transactions manually. `Builder` will be the set of helpers so instead of `[retain:5, insert:f, insert:o, insert:o] one can call simple `builder.addChildText( p, 'foo' );`.

**Comment by Tade0** [comment]
Are we going to instantiate the Builder each time we're in a new closure?

**Comment by pjasiun** [comment]
More-less. Actually every time you want to change something in the document you create an instance of the `Builder`, use its methods to modify document (create, remove or change nodes, add attributes and so on), then render your changes and save the undo step. So if you want to have two separate undo steps you will create two separate `Builder` instances.

**Comment by Tade0** [comment]
I'm smelling feature envy here.
https://sourcemaking.com/refactoring/feature-envy

Since the main purpose of the Builder is to modify the document, isn't the Builder a _trait_(as in Scala Traits) of the document?

If it were a trait, we could have this syntax:
```
document
  .addAttribute( range, bold )
  .render();
```

In this example addAttribute and render are methods of the Builder(or other name here) trait which return the document instance or a promise - depending how we design the Builder trait.

**Comment by fredck** [comment]
I'm also finding the need of the builder strange. Why not having the tools directly into the document? Then, what if `document.render()` (or `document.commit()`) would simply render all the pending transactions in the document?

**Comment by pjasiun** [comment]
First of all I believe there should be the separation between the document model and one who change it (lets call it controller). I have nothing against modification methods in the document (`document.addAttribute( range, bold )`). But the problem is who contains collection of changed nodes needs to be rendered and list of transactions to save them. I do not think it should be document. Document contains data, can be serialized, if need to. List of recently changed nodes and transactions to be saved as a undo step should be handled by someone else, the mentioned controller.

So in terms of properties:

### Document:

 * linear data,
 * document tree,
 * attributes repository.

### DocumentControler or Builder:

 * changed nodes to render,
 * applied transactions to be saves as an undo step.

In terms of methods the main entry point for all document changes will be `applyTransaction` which return the list of changed nodes. All other methods will build a transaction and apply it. This way we have two levels of the interface:
 * `applyTransaction` - which is a low level interface,
 * all ~~humal~~developer-readable methods (like `addAttribute`) - which is the higher level interface.

I think that having two level of the interface in the same class is a bad design. The proper way is to have `applyTransaction` as an document interface and `addAttribute` as a DocumentControler/Builder interface, together with its properties. The fact that these higher level methods are together with properties which hold information about the change is even more important: otherwise (if `addAttribute` would be in the document) user would need to get transaction and changed nodes and store them in the controller every time.

Now.

The question is: should there be a single `DocumentControler` which has a `render` (or `commit`) method which apply all changes since the last `render` and save the undo snapshot automatically or an instance of it (`Builder`) for every change. I think the first solution has 2 limitations:
 * What with changes which were already applied to the document and do not need to be rendered (e.g. typing)? We could have an additional method or a parameter for the render/commit method to only move the last synchronization point, but it looks like hacking the solution from the begging.
 * We limit the solution to the synchronized changes. With the `DocumentControler` there must be a strict order of the changes. We introduce the whole operations transformation mechanism to make our solution more generic. It should be possible to update two undo steps separately. For example if the image in uploading and user is editing document at the same time each will have its own undo step he apply changes to. It is definitely possible with the operation transformation.
But on the other hand, I have to agree that having single `DocumentControler` would make the code simpler in the basic cases.

**Comment by pjasiun** [comment]
I have an idea that creating undo steps could works automatically for the code like this:
```
    var step = editor.newStep();
    step.addAttribute( range, bold );
    step.render();
```
So all changes applied on that step would automatically create an undo step.

**Comment by Tade0** [comment]
> First of all I believe there should be the separation between the document model and one who change it (lets call it controller).

This goes against encapsulation. An object should directly modify only data which it owns.

>I think that having two level of the interface in the same class is a bad design.

Actually, this is pretty common. Usually the lower level is private (or _protected_).

As an example: Say we have a complex number class.
The low level interface consists of properties: imaginary part, real part, angle, magnitude.

We could make them public, but that could introduce errors and would be confusing for the end user, so we make them private (protected).

The high level interface consists of methods for data retrieval and modification. This one is public.

Do we need some kind of ComplexNumberController here? No, because it brings no additional benefit, it increases complexity and additionally if it were to hold state (if it weren't static), it would have to keep track of the ComplexNumber class either by busy waiting or being notified of changes by the ComplexNumber class, which in turn would require the ComplexNumber class to have knowledge of it's controller.

One-to-one relationships are suspicious by default and usually mean, that the two related objects should in fact be one.

**Comment by jodator** [comment]
@Tade0: I think that you missing the point of the step or @pjasiun has different idea about that class that I have in my mind :). 

As see this way: you can use either a create a `CollectionOfTransformations` aka `Step` by hand or use a specialized builder which will help you do this. I don't see a one-to-one relationship problem here.

So basically we do not construct here a "simple" number (`ComplexNumber`) but rather an operation/step that is collection of `ComplexNumber` and some operations on them. Doing simple operations like `ComplexNumberAdd` can be writen quickly by dev, but doing some more complex operations in one step (reversible) can be written as a collection of `ComplexNumberOperations` which involves some deeper knowledge on how to make them. Here can be used a `ComplexOperationBuilder` that will be a simpler interface for building that operation.

Also I don't think that `ComplexNumber` should know anything about `ComplexOpertaionBuilder` in fact it is the opposite way.

The only problem I see is that I don't think that `CollectionOfTransformations` should know how to render itself: `step.render()` which in my feeling should be separated.

**Comment by pjasiun** [comment]
> @Tade0: I think that you missing the point of the step or @pjasiun has different idea about that class that I have in my mind :).

@jodator is right and explained it very well. `applyTransaction` is a valid interface, but for people who want to create transaction manually. Some plugins (like collaboration editing plugin) will use this level of the interface.

> The only problem I see is that I don't think that CollectionOfTransformations should know how to render itself: step.render() which in my feeling should be separated.

Separating renderer and `CollectionOfTransformations` makes sense, so `renderer` will simply get this collection as a parameter. In fact `CollectionOfTransformations` should know nothing about rendering.

The question is how to make the most common operation which is "apply some changes, render them and save the undo step" as simply as possible. But on the other hand using 3-4 lines of code to do it is not that complex and we get good logic separation thanks to is, so maybe we should not try too hard to reduce it to the 1-2 lines of code.

**Comment by Tade0** [comment]
>But on the other hand using 3-4 lines of code to do it is not that complex and we get good logic separation thanks to is, so maybe we should not try too hard to reduce it to the 1-2 lines of code.

It's not about the lines of code, but the complexity and maintainability.

I think that if you want to do it this way then we should make use of the _factory_ pattern.

This way:
-A `Transformation` would be no more than an array of low-level operations.
-A `Step` would be no more than an array of Transformations.
-The `TransformationFactory` would be ideally static and have methods for creating/combining Transformations.
-The `document.render()` method could accept a Step or a Transformation.

which would let us write code like this:
```
document.render( TransformationFactory.addAttribute( range, bold ) );
```

```
var tf = TransformationFactory,
  step = [
    tf.addAttribute( range, bold ),
    tf.doSomethingComplex( param1, param2 ),
    tf.doEvenMore( param1, param2, param3 )
  ];
document.render( step );
```

With this design:
-The _concerns_ are separated.
-There are no superfluous classes.
-Simple operations can be done with an obvious one-liner.

**Comment by pjasiun** [comment]
First, do not use the term `Transformation` in this context, because `Transformation` is the [operation transformation](http://www.codecommit.com/blog/java/understanding-and-applying-operational-transformation) or transforming Document Model to the the Dirty DOM and back. Yep, we definetly need the dictionary, as soon as we set all basic names we use.

Second: step can not be a simple array. Every `tf` method will returned set on nodes which were changed. And step should merge them, reduce duplicated. It could be done by the `render` method, but if you also use the same step to save an undo step then you will need to do the same work twice. So the `Step` can be an object with the `add` method.

Also note that every of these methods will modify the document, because the next one need to work on the modified document to create a proper operations for it. This is why it is not a simple factory and calling it this way it would be misleading.

Of course we could separated everything. Then we would have:
```
var of = OperationsFactory( document ),
    step = new Step(),
    trasaction, changedNodes;

trasaction = of.addAttribute( range, bold ); // a.k.a Delta
changedNodes = document.applyTrasaction( trasaction );
step.add( changedNodes );

trasaction = of.doSomethingComplex( param1, param2 ),
changedNodes = document.applyTrasaction( trasaction );
step.add( changedNodes );

trasaction = of.doEvenMore( param1, param2, param3 ),
changedNodes = document.applyTrasaction( trasaction );
step.add( changedNodes );

document.render( step );
```
Separation is great, but I think it is too complex for the simple change.

**Comment by Tade0** [comment]
>Also note that every of these methods will modify the document, because the next one need to work on the modified document to create a proper operations for it. This is why it is not a simple factory and calling it this way it would be misleading.

That's the whole point of factories. You have an object that _holds state_ and it's main task is to create other objects based on that state.

>Every tf method will returned set on nodes which were changed. And step should merge them, reduce duplicated.

Why is this Step's responsibility? It's the document that owns this data, especially the information about the nodes that were changed.

**Comment by pjasiun** [comment]
> > Every tf method will returned set on nodes which were changed. And step should merge them, reduce duplicated.

> Why is this Step's responsibility? It's the document that owns this data, especially the information about the nodes that were changed.

Document do not know how many recent changes should be rendered. See: https://github.com/ckeditor/ckeditor5-core/issues/35#issuecomment-127972924

**Comment by pjasiun** [comment]
The conception changed and simplified a little in the meantime. Now it is handled by: https://github.com/ckeditor/ckeditor5-core/issues/69
