### ISSUE TITLE
Confusing Model's variables naming (attribute vs property)

### ISSUE THREAD

**Issue by jodator** [ckeditor/ckeditor5-core#36]
I've just like to let you know that differentiation between Model's `property` and `attribute` is not clear.
I get the impression that is a "potato, potato" problem - https://github.com/ckeditor/ckeditor5/issues/26#issuecomment-137654904.
After talking with @pjasiun I get that attribute is a property that someone can listen to its changes.

This might give some problems:
- Newcomers would have to read a documentation on in and remember which one is which.
- For me `attribute` and `property` are [synonims](http://www.thesaurus.com/browse/attribute) which other devs might found confusing - again one will have to remember which one use in which case.

Maybe giving `attribute` more meaningful name would make sense?
Ideally no docs should be needed or name would be connected to function so it will be easily remembered.

**Comment by fredck** [comment]
That's all about MVC naming, in fact. I mean, the difference between attributes and properties. Btw, having attributes changes on events is just an extra feature. The key semantical difference, in MVC terms, is that attributes are part of the model while properties are not.

Some MVC frameworks isolate attributes under a main "attributes" property. This is ok if the objects are used exclusively for MVC purposes. In our case, they are also part of the editing API, so isolating them would not be useful.

For example: `Person.name` vs `Person.attributes.name` vs `Person.nameAtt`. If `Person` is part of the application API, it is expected that `Person.name` will be available. If `Person` is a pure MVC class, the `Person.attributes.name` would be fine, but people would be using `Person.get( 'name' )` instead. No matter which intent though, `Person.nameAtt` would be weird.

So, I don't see much options for us other than proper documentation. In fact, @Reinmar commented yesterday about using `@property` and `@attribute` (custom tag) to document things accordingly.

**Comment by fredck** [comment]
In fact @Reinmar's proposal is here: ckeditor/ckeditor5#26

**Comment by jodator** [comment]
@fredck: The main point is that the names are still confusing and I just wanted to point it out.
I don't get why `attribute` is part of the model and why `properties` are not - while semantically are very similar (if not a synonyms).

Also I think, that this has nothing to do with ckeditor/ckeditor5#26 since that issue is ok - the `@attribute` thing should have a separate annotation - I was just wandering if a name for this is accurate enough while coexisting with `property`.

Also I've pointed it out because attribute/property seems as a base API which should be clear and understandable and in my feeling they names doesn't express they purpose clearly enough for an outsider.

**Comment by fredck** [comment]
This terminology is inherited from Backbone, in fact. It is important to have a good understanding of what is "model state" and to understand that Attribute is for Model what Property is for Objects.

In other words, if you see an object as Model, you look for Attributes... if you see it as a JavaScript Object, you look for Properties.

**Comment by jodator** [comment]
@fredck ok, fair enough
