### ISSUE TITLE
PluginCollection should not turn a meaningful error into meaningless "this plugin could not be loaded"

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-core#40]
See https://github.com/benderjs/benderjs/issues/245#issuecomment-138467961.

The reason why this happens is that a normal error (e.g. syntax error) is turned into `CKEditorError` with a useless message.

There are three options:

1. Either don't throw `CKEditorError` but the existing error (which is available as an argument of that callback).
2. Throw `CKEditorError` with the current message but log the original error to the console.
3. Throw the original error but log to the console that a plugin could not be loaded.

The second option is more complicated, but perhaps it's a rare case, so maybe we don't have to worry about that complexity.

**Comment by Reinmar** [comment]
Any other option that 1. seems to be overcomplication, but I think that it's a quite useful thing that our error precisely indicates that a plugin didn't load.

**Comment by pjasiun** [comment]
I think we should focus on our needs.

In the debug mode we need to have as many useful information as we can, served in the best possible way. Browsers show nice stack trace and let us use `debugger` so we should keep the original error. The additional message which plugin crashed is also useful, so I am for the option no. 3 for better debugging.

For the final version it would be great if the plugin error do not crash editor, but only log the information what is wrong and disable the plugin. Thanks to this we could throw an error in the plugin if a needed config is not defined. Also if a user add bad-quality third-party plugin which have errors it should not crash the editor, but be simple disabled. We should log an error in such case too, let the user debug it, but debugging is not a priority in such case.

So I think we should have two solutions depend on `CKEDITOR.debug`.

**Comment by pjasiun** [comment]
Also I do not know o what level errors should be cached (in the production version) not to stop any other code.

**Comment by Reinmar** [comment]
> For the final version it would be great if the plugin error do not crash editor, but only log the information what is wrong and disable the plugin.

This is an interesting point – what should happen with the error later on. Should it stop editor creation? I think I'm for crashing as early as possible, so if some plugin wasn't able to initialise, that should stop editor creation. Otherwise, we may run into strange problems like, what if plugin B requires plugin A, when plugin A crashed? Is plugin A initialised? How can B use A if A crashed? How long is it going to work? I believe that regardless of the mode you're in, the answer is that the sooner it crashes the better. If it crashes on production sever for the users, it's of course a pity. But at least it will be clearly and quickly visible to developers of that website or of that plugin that something doesn't work.

Anyway, this is a topic for another discussion, as this specific decision must be made in a different part of the code (the `Editor` class I guess). As for the original question that I asked, we are both in favour of option 3., so I'll implement it.
