### ISSUE TITLE
Implement useful collection methods for Collection and NamedCollection

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-core#49]
Requires: #48.

That would be at least: `map()`, `forEach()`, `has()` and perhaps also `filter()` and `find()`.

We already have couple of usecases in which we missed these methods – e.g. inside `editor#init()`. If we'll not have them now, we'll keep using `for()` loops for everything.

BTW. Inside PluginCollection I already had to implement `forEach()`.

**Comment by Reinmar** [comment]
Instead of implementing `has()` we can avoid throwing inside `get()` would make more sense (less code).

**Comment by Reinmar** [comment]
It's also a good question whether it's useful when `remove()` throws. It depends whether we want the code to be more safe, but then you need to check with `get()` if something exists before removing it. Or whether we want to KISS, but then we risk that someone will be removing stuff that doesn't exist what will  hide some bugs.

**Comment by scofalik** [comment]
I think that the code should throw. I don't think it's against KISS policy and, as you said, it will make bugs more visible and easier to track. It's better to make sure that you remove existing stuff (use try if you have to) than debug why code crashes in a totally different part of project.

**Comment by Reinmar** [comment]
> Instead of implementing has() we can avoid throwing inside get() would make more sense (less code).

Turns out that `PluginCollection` already worked this way :D.
