### ISSUE TITLE
Introduce the Editable class (controller and view)

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-core#53]
We need a basic Editable class plus at least two concrete implementations – inline and framed (`ckeditor5-plugin-editable-inline` and `ckeditor5-plugin-editable-framed`).

**Comment by Reinmar** [comment]
After some thinking I realised that I need @oleq's UI core library to implement editables. As every UI component editable has a view and and a model, plus, in case of such complex entities as editables it may be good to have a dedicated controller (although I could agree to have M+C together). However, the most important part is how V and M are connected and that will be solved by the UI core lib. Hence, it does not make much sense to work on anything specific before we have something from the UI core lib.

Other notes:

* Editable can have nested editables (like view can have nested views).
* Similarly to views, all editables need to be registered in one focus manager.
* Some editables will initialise asynchronously.

**Comment by oleq** [comment]
> However, the most important part is how V and M are connected and that will be solved by the UI core lib.

It's working, see the https://github.com/cksource/ckeditor5-core/tree/ui branch. It would be a great opportunity to improve View's interface anyway if we implemented Editable class on top of it..
