### ISSUE TITLE
Move PluginCollection and Plugin to utils

### ISSUE THREAD

**Issue by pjasiun** [ckeditor/ckeditor5-core#57]
What `Plugin`/`PluginCollection` are, is the util to solve problems with the dependencies tree. It's enough to rename `editor` variable to `context` and change docs to make it more flexible util. It's very helpful to split a project into pieces, event if it is editor-independent.

Note that it's possible to make it compatible with the editors plugins:

```js
export default class Plugin {
	constructor( contex ) {
		_.extend( this, contex );
	}

	// ...
}
```

```js
export default class Editor {
	constructor( config ) {
		this.plugins = new PluginCollection( { editor: this } );

		// ...
	}

	// ...
}
```

**Comment by pjasiun** [comment]
Also, I think it would be a good change in general. A class should do one task. This class has a task to solve dependencies and it is what it really do. Making it a util lets developers understand it easier.

**Comment by Reinmar** [comment]
Makes sense. Then `Plugin` becomes a util as well :D But in fact, I was rather planning to make `Plugin` an interface, so we could do both things at the same time. Although, the latter is a bigger change, unfortunately.

Related ticket: https://github.com/ckeditor/ckeditor5-core/issues/54.

**Comment by Reinmar** [comment]
But I don't like this for CKEditor:

```js
_.extend( this, contex );
```

We should keep the `editor` param (so the ctx of Editor#plugins will be the editor itself).

**Comment by Reinmar** [comment]
This should be handled together with https://github.com/ckeditor/ckeditor5-core/issues/78.

**Comment by Reinmar** [comment]
BTW, soon we'll make commands and command collection utils too and ckeditor5-core will become a set of utils and interfaces (cause editor will be an interface too).

**Comment by Reinmar** [comment]
Closing due to lack of interest in this now.
