### ISSUE TITLE
Use Set as a base for Collection

### ISSUE THREAD

**Issue by oleq** [ckeditor/ckeditor5-core#58]
1. Accessing collection items with indexes (like get) is rare.
2. In most of the cases a `NamedCollection` is used instead
  1. Like in. `PluginsCollection` (already using it).
  1. Like in `CKEDITOR.instances`. `CKEDITOR.instances.get( 3 )` has no meaning, and even less when instances are removed and added – which one is `3` when indexes change anyway?
3. Set guarantees unique items in the collection by default.

**Comment by Reinmar** [comment]
There are couple of interesting observations here that I'm glad we've made now.

1. So far we used the `Collection` class for most of the things (editors, editables, etc). We pretended that they are accessible via `get( index )`, but the index of a single item may change as other items are removed from the collection. So basically there's no `id` of any kind.
2. Backbone's models have identifiers and can be retrieved from the collection by them. What's more – backbone collections can be accessed by `at( index )` and `get( id )` at the same time. 
3. We used to have named editors and editables (nested ones are also named in CKE4). This is really useful when working with these items as it allows you to quickly notice some issues. All of us agreed that those items should be named (the names can be stringified numbers).
4. It was hard for us to find some cases in which you usually wouldn't want to access items in the collection by some id. One of the examples were upload transfers.

Anyway, my proposal is that we should have one collection class based on Backbone's collection. This means that all models must be named (names can be automatically generated) and that collection will be array-based to provide an order but also object-based for "by id" access. It works for Backbone and we shouldn't reinvent the wheel.

**Comment by jodator** [comment]
> Accessing collection items with indexes (like get) is rare.

I'm using this while doing keyborad navigation in files pane.

```js
// Let's say some one hits arrow down, no index boundaries checking, etc
var currentIndex = collection.indexOf( item ):
var nextIndex = currentIndex + view.getRowSize();
var toFocus = view.getByModel( collection.at( nextIndex ) );
```

Order of items in collection is in line with collection's sort function in that case.

> This means that all models must be named
Backbone have `model.cid` property which is used to compare them.
Unique id is probably taken from `_.uniqueId()` - which is simple wrapper for incrementing some var by 1.

Basically each mode/collection/view has it's `id` which I'm probably using when comparing two objects.

> Set guarantees unique items in the collection by default.

Backbone's Collection is also unique by default (I cannot add the same model to collection, but I can probably create two models with the same values - ie when adding simple object to collection).

Also collection have `_byId` object which is probably used to achieve above.

Collection has length property and can be used as array (`splice`, `push`, `pop`, etc)

I haven't any significant issues with collections.

Also something I have noticed:

When you add a model into collection it will have an `collection` attribute (I don't remember the lingo you're using but it is on model object a not accessible by `model.get( 'collection' )`.

Collection can have a default model class, so doing this:
```
var collection = new Backbone.Collection({ model: MyModel });
collection.add( { name: 'a' } );
// is the same as
collection.add( new MyModel( { name: 'a' } );
```

**Comment by jodator** [comment]
Regarding ID - I think that probably each object has unique ID across app so there shouldn't be any view that have the same `.cid` as some model or collection.

**Comment by fredck** [comment]
I don't think we need to implement 1 to 1 the features Backbone provides, but I'm fine with introducing uID to models. And ofc, accessing by index is still a basic collection feature that we must keep.

**Comment by Reinmar** [comment]
> I don't think we need to implement 1 to 1 the features Backbone provides, but I'm fine with introducing uID to models. And ofc, accessing by index is still a basic collection feature that we must keep.

I agree. I didn't mean to try to copy Backbone 1 to 1, but I noticed that instead of overcomplicating things with two classes we can go with just one. I'm open to how we'll implement it – e.g. IMO we can leave without globally generated uIDs. Having just a locally generated names (e.g. the Editor constructor using it's own counter) is OK for me too.

**Comment by Reinmar** [comment]
I reported #77 summarising this discussion and some discussions that we had internally. I'm closing this ticket as invalid.
