### ISSUE TITLE
Node list compression

### ISSUE THREAD

**Issue by pjasiun** [ckeditor/ckeditor5-core#62]
Because every character is now a separate class, tree model can consume a lot of memory. The situation is event worse because model will keep the history of changes including all historical nodes and operations with lists of nodes to change.

The solution is to introduce compression inside `NodeList` class which is used for both operations and child list. The idea is to keep existing interface with characters as children, but to implement it internally in the way that all siblings characters with the same attributes will be stored as as a single `Text` (string with attributes). 

Then characters may be a proxy witch act like a single character, but have reference to the whole text and modify it if characters attribute changes. The character class does not need to be lightweight anymore, because there will not be many references to these classes kept in the code.

If user call `getChild` at the middle of the string the new character class will be created with the reference to that string. Disadvantage would be that it will not be possible to simple compare references to two characters, but is does not seems to be a common operation. On the other hand, it will be possible to get `Position` before/after both character and compare them.

This mechanism needs to be smart. The most common operations should work fast, without creating a special API for them. For example consider changing attribute on the set of following characters (like applying bold on the range). The change attribute for the character should check if the new list of attributes is the same as the list of attributes of the previous text and move that character to the previous text. Special method to apply style on the range would work faster, but having separate API to work on whole text nodes is something we want to avoid, at least at the begging.

Thanks to this compression we will not only save memory because of having less character classes, but also reduce number of attributes and maybe be able to change the attribute data structure, which is getting strange and slow because of decisions to save memory.

**Comment by scofalik** [comment]
Here is the new behavior of `NodeList`:

We have `Text` class, which is only for representing a string with attached attributes to it. It is mostly used to append characters with set attributes to `Element` instances. `Text` is not a `Node` class.

We got rid of `Character` class and introduced similiar `TextNode` class. `TextNode` is extending `Node` class. It is used as a representation of some text in tree model. This class is a bit weird but is a best consensus between user expectations, code efficiency, API complication and amount of time spent coding it.

`NodeList` does not contain singular characters like before. Now all consecutive characters with same attributes are kept as one instance of `Text` class. So internal `NodeList` array is keeping instances of `Element` and `Text` inside it. Still, outside, characters are visible as singular beings. So if your `NodeList` contain a `P` element, `foo` string and `DIV` element if you iterate over it (without merging characters) you get `P` element, `f` text node, `o` text node, `o` text node, `DIV` element. Similary, when you use `nodeList.get( 3 )` you will get `o` text node.

`TextNode` is kind of a "readonly proxy" to the characters that are contained in the `NodeList`. It looks like a `Node` with some exceptions. Most notably, any changes done to `TextNode` are NOT reflected on original `Text` object. This is mostly okay - all in all changes to tree model should be done via batch. Internal methods, on the other hand, use references to original `Text` object to operate on them.

You can have multiple different `TextNode` connected with `Text` object. `TextNode` may be one or more characters from original `Text` object. `TextNode` has reference to original `Text` object (protected), `start` offset in original object (protected) and text that the `TextNode` is representing (public). Also it inherits everything from `Node` but `parent` property is readonly.

Now that we touched `parent` property there is one dirty thing that I don't like but live with. As I said, `NodeList` keeps `Text` and they are referenced in `TextNode`s. But `Text` is not a node, so it does not have `parent`. I could go with two solutions:

* introduce third class that would be basically `Text` with parent property and would be used only in `NodeList` and as a reference in `TextNode`, or
* leave `Text` as is but add `parent` property when adding `Text` to a node.

I've gone with the second option. If you think it is too dirty and "silent", I will introduce some kind of `NodeListText` class that will inherit from `Text` and add `parent` property.

Another solution that would solve some problems would be keeping `TextNode` in `NodeList` and keep reference to original `TextNode` in a `TextNode`.
