### ISSUE TITLE
Data structure for attributes

### ISSUE THREAD

**Issue by pjasiun** [ckeditor/ckeditor5-core#63]
To save memory, attributes are instanced of `Attribute` class which can be reused. We introduced special method to force `Attribute` reuse (`Attribute.register`). Then, not to split this attributes into separate key and value, node contains a `Set` of attributes.

The problem is that then attributes are not stored by key all attribute operations (`hasAttr`, `getAttr`, `setAttr`, `removeAttr`) need to scan whole set, what is very ineffective. During the text transformation from the Tree Model to DOM every pair of siblings needs to be compared to ensure that attributes do not change.

When the node compression will be done (#62) there will be less attributes stored and the memory usage may not such a be a problem anymore. Then we could store attributes in a map, instead of set, where the attribute key will be a map key and whole attribute or the attribute value will be a map value. 

Also current way of compering attributes will need to be changed. Now the `_hash` attribute is kept which is build from the key and value. If they will be stored and compared separately we could build `_hash` only from value. Or we could consider storing values stringified.

Finally `Attribute.register` may not makes sens after these changes, becoming an unnecessary complication.

**Comment by scofalik** [comment]
While I was reviewing your code I also thought that `Attribute.register` is/will be obsolete.

**Comment by pjasiun** [comment]
From https://github.com/ckeditor/ckeditor5-core/issues/33#issuecomment-154115418:

> Expose sort() from attrubute's constructor (for both – memory and testability reasons). (I know there's a plan to refactor this bit)
> Explain what sort() actually does. Not what it does not do.

**Comment by scofalik** [comment]
First step will be moving attributes API to `AttributeList` class.

**Comment by scofalik** [comment]
We decide to move attributes API to `AttributeList`. Prior to this, only `Node` class used attributes and it had methods like `setAttr` or `removeAttr`. After introducing `Selection` we expect that more class may use attributes, to everything related to them got moved to `AttributeList`. We also expect that we might use multiple `AttributeList`s for one class (i.e. attributes and meta attributes which will be special case of attributes).

**Comment by scofalik** [comment]
`AttributeList` has been introduced and it extends ES6 `Map` class. Characters in `NodeList` are now compressed, so less `Attribute` instance is used per character. `Attribute.register` has been removed. See PR #139

**Comment by pjasiun** [comment]
As a follow-up of https://github.com/ckeditor/ckeditor5-core/pull/139 we decided to fix the hacky way how `AttributeOperation` handle `TextFragment`s as a part of this ticket.

**Comment by pjasiun** [comment]
The magic has gone.
