### ISSUE TITLE
Model.set should not allow to override an existing property

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-core#74]
We've run into an ugly issue by doing:

```
model.set( 'on', false );
model.on( 'change:on', ... );
```

and boom! :D 

So I would like if `set()` threw.

**Comment by oleq** [comment]
:+1:

**Comment by Reinmar** [comment]
Quoting myself from the PR:

> I remember I proposed this already like 1y ago that instead of model.set() we should have model.define() which could only be called once to define an attribute, but later on it would just throw. Otherwise, we may have the same issue with overriding model attributes by its ancestor class. I can propose such change as a followup, but I would like to close this ticket first.
