### ISSUE TITLE
Fix the collections

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-core#77]
Followup of #58.

We decided that a single `Collection` class with functionality of both – unordered map and an ordered array will make the most sense. There will be no ambiguity which collection to choose for the specific case that you're dealing with and you won't need two collections when you need to store named items, accessible by names, but also ordered.

The changes:

1. Remove `NamedCollection`.
1. Add `Collection._modelMap`.
1. Change `Collection.add()` so when adding a model without an `id` it's automatically generated.
1. `Collection.add()` should accept all objects, not only models. That will guarantee that we'll be able to generate collections of other kinds of objects.
1. Allow configuring the name of the property which represent's model `id` (e.g. to `name`).
1. Add  `Collection.at( index )` and `Collection.get( id )`.
1. Change `Collection.remove()` to accept id (when a string), index (when a number) or a model (when an object).
1. Remove `forEach()` but add an iterator. Add `map()`.

**Comment by fredck** [comment]
> Add Collection.at( index ) and Collection.get( id ).
> Change Collection.remove() to accept id (when a string), index (when a number) or a model (when an object).

There should not be different approach on these two cases, right? Either `get()` works like `remove()` or vice-versa.

**Comment by Reinmar** [comment]
> There should not be different approach on these two cases, right? Either get() works like remove() or vice-versa.

You're right. WDYT about having `remove()` and `splice()`? After a bit of thinking I would like to avoid having one method which accepts 3 types of argument, because it may be a cause of issues. You may think you have your `id` in a string, but by mistake you may pass it as a number. Plus, `splice()` allows to do more.

**Comment by fredck** [comment]
I'm for making it simpler and avoiding introducing methods that we no even know we need them. String vs Number sounds fine for me.

**Comment by Reinmar** [comment]
We can be sure that we'll need to remove some items based on their indexes like we can be sure that we'll need to iterate over them or map them. It's inevitable. If we won't create methods for that now, we'll need to constantly work on this class which is disturbing.

As for string vs number – I just had this bug in my code. So I would really like if `get()` and `remove()` would accept only ids and items.

**Comment by oleq** [comment]
> WDYT about having `remove( idOrItem )` and `splice()`?

It's counterintuitive. There will be lots of questions like "Why doesn't `remove()` work with indexes?" and so on.

> You may think you have your id in a string, but by mistake you may pass it as a number. Plus, splice() allows to do more.

Yeah. And this is why there should be `Collection.remove( id | index | object )` + `Collection.splice()`. There will always be bugs. But I wouldn't make the API *exotic* to eliminate a single, hypothetical source of problems.

**Comment by Reinmar** [comment]
And in this case you would merge `get()` and `at()` into `get( id | index | object )`, right?

If both of you agree, then let it be.

**Comment by Reinmar** [comment]
(PS. I edited the previous comment, because get() does not have to return an item by item :D.)

**Comment by oleq** [comment]
:+1:

**Comment by fredck** [comment]
:+1:

**Comment by Reinmar** [comment]
Voila!
