### ISSUE TITLE
Elements are checked twice

### ISSUE THREAD

**Issue by pjasiun** [ckeditor/ckeditor5-core#84]
Here: https://github.com/ckeditor/ckeditor5-core/blob/master/src/document/operation/changeoperation.js#L105
and here: https://github.com/ckeditor/ckeditor5-core/blob/master/src/document/operation/changeoperation.js#L81

We checked  and change elements twice, because the `value.node` will be the same for `value.type == ELEMENT_ENTER` and `value.type == ELEMENT_LEAVE`.

We could add the check there but we could also consider not returning closing tags if you iterate over the range this way, because it is very easy to create a bug like this.

On the other hand I met this problem in the CKE4 that walker do not return closing tags and I believe that it is easier to add `if` statement and ignore closing tags, when we do not need them, than trying to get them somehow, if the iterator does not return them.

**Comment by pjasiun** [comment]
This should be also fixed for the change delta. There is a missing test for some cases connected with closing tags:

 - add attribute on the range which starts at the end of the last child element and ends after the parent element, so the range contains only closing tags,
 - ensure that attribute is not set twice if the range contains opening and closing tags,
 - change attribute delta, if there was a different attribute on the character before the closing tag and different attribute on the character after it,
 - change attribute delta, if there was the same attribute before and after the closing tag, but the element which is closing has a different attribute,
 - various ranges containing closing tags and other element with various attributes,

The correct behavior is that changing attribute on the closing tags should do nothing, closing tags should be transparent for the change operation and change delta.

**Comment by scofalik** [comment]
I've fixed the issue in `ChangeOperation` and `ChangeDelta`.

For `ChangeOperation`, I've added two tests with an operation that tries to add/remove attribute on a range that contains "closing tag".

For `ChangeDelta` we should mainly check if operations are not created when they are not needed. The delta result is less important as it is already covered in `ChangeOperation`. Of course I also check the result but I want to stress out what is more important for those tests.

> add attribute on the range which starts at the end of the last child element and ends after the parent element, so the range contains only closing tags,
I've added a test that removes an attribute from a range that contains only closing tag. There should be no operations created for that delta.

> ensure that attribute is not set twice if the range contains opening and closing tags,
Modified a test and changed if there is a proper number of operations created.

> change attribute delta, if there was a different attribute on the character before the closing tag and different attribute on the character after it,
This should get splitted no matter what attributes are on closing tag.

> change attribute delta, if there was the same attribute before and after the closing tag, but the element which is closing has a different attribute,
In this case nothing should happen (by that I mean that the operation should not get split). This is covered by one of tests I created ("closing" element has an attribute but it's children and siblings does not have it). The operation is not splitted.

For now I have changes on t/84 which was created from t/59-r. I'll make PR after t/59-r is on master.

**Comment by pjasiun** [comment]
Sounds good. I am waiting for PR to close it :)

**Comment by pjasiun** [comment]
> I've added a test that removes an attribute from a range that contains only closing tag. There should be no operations created for that delta.

I've added test that add an attribute to a range that contains only closing tag. It causes error. The same for collapsed range.

**Comment by pjasiun** [comment]
I created additional tests and pushed them to the https://github.com/ckeditor/ckeditor5-core/tree/t/84b. 3 tests are red.

**Comment by scofalik** [comment]
I'll check it and make a PR with those fixes.

**Comment by scofalik** [comment]
I force-pushed t/84b with new commit.

**Comment by pjasiun** [comment]
Closed via https://github.com/ckeditor/ckeditor5-core/pull/109.
