### ISSUE TITLE
Use a simpler plugin naming scheme

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-core#85]
In https://github.com/ckeditor/ckeditor5-core/issues/27 we introduced plugin names.

We decided to go with a `Plugin.pluginName` static property instead of `Plugin.name` because the latter is reserved by JS and equals the name of the function which is the constructor of the plugin. Back then this boiled down to two reasons:

* `Plugin.name` wouldn't give us a full flexibility in terms of what goes where (and we wanted to use `'pkg/module'`  strings).
* `Plugin.name` will be affected by code minification.

The latter still stays true. This is a result of running Babili on CKEditor's source:

```js
class P extends h.a{static get requires(){return[w.a]}static get pluginName(){return'image/imagecaption'}}u.a=P}
```

However, perhaps we should simplify the naming scheme. I saw in the documentation which @fredck wrote for builds that he intuitively assumed that it will look like this:

```js
// Define the full list of plugins to enable.
ClassicEditor
	.create( document.querySelector( '#text-editor' ), {
		plugins: [ 'Paragraph', 'Heading', 'Bold', 'Link' ]
	} )
	.catch( error => {
		console.log( error );
	} );
```

So that we'll use the class names. @pjasiun proposed something similar.

This means that name collisions may be more frequent, but it's easier to understand for the developers. Also, the collisions should be rather theoretical because you shouldn't have two plugins with the same name in one build (as they'd duplicate themselves). 

If anyone is ok with this, let's change the naming convention. It'd only require a warning (will be enough) in the plugin collection that a plugin with an identical name is already loaded and this may lead to unexpected behaviour.

**Comment by oskarwrobel** [comment]
What about UI component names? Still lowercase?
```
Editor.create( element, {
	plugins: [ 'Bold', 'Italic', 'Link', 'Undo' ],
	toolbar: [ 'bold', 'italic', 'link', 'undo' ]
} )
```

**Comment by Reinmar** [comment]
Yeah, I noticed this when writing guides for builds. TBH, I don't know... This is the moment when sticking to a code naming convention leads us to troubles. Plugins are named after classes and buttons are not necessarily (so they are simple map keys).

I can see  two options:

* Claim that components are named after classes too (and use uppercase names).
* Make component factory case insensitive (this is actually always good in such places).

**Comment by oleq** [comment]
> Claim that components are named after classes too (and use uppercase names).

It doesn't make sense IMO. E.g. the `Link` class delivers both link and unlink button. There's no such thing as `Unlink` class.

> Make component factory case insensitive (this is actually always good in such places).

👍 

As for general simplification of the plugin naming, I'm for it.

**Comment by pomek** [comment]
What do you think about adding to the `Plugin` class default value for `Plugin.pluginName`? If we want to simplify the names, we can use name of class as a plugin name:

```js
class Plugin {
    /* ... */

    static get pluginName() {
        return this.name;
    }

    /* ... */
}

class SomeExtraPlugin extends Plugin { }

console.log( SomeExtraPlugin.pluginName ); // 'SomeExtraPlugin'

**Comment by Reinmar** [comment]
That's not going to work with code minification.

**Comment by pomek** [comment]
For the following packages I changed plugins' names and fixed tests:

* [ckeditor5-autoformat#t/ckeditor5-core/85](https://github.com/ckeditor/ckeditor5-autoformat/compare/master...t/ckeditor5-core/85)
* [ckeditor5-block-quote#t/ckeditor5-core/85](https://github.com/ckeditor/ckeditor5-block-quote/compare/master...t/ckeditor5-core/85)
* [ckeditor5-basic-styles#t/ckeditor5-core/85](https://github.com/ckeditor/ckeditor5-basic-styles/compare/master...t/ckeditor5-core/85)
* [ckeditor5-clipboard#t/ckeditor5-core/85](https://github.com/ckeditor/ckeditor5-clipboard/compare/master...t/ckeditor5-core/85)
* [ckeditor5-enter#t/ckeditor5-core/85](https://github.com/ckeditor/ckeditor5-enter/compare/master...t/ckeditor5-core/85)
* [ckeditor5-image#t/ckeditor5-core/85](https://github.com/ckeditor/ckeditor5-image/compare/master...t/ckeditor5-core/85)
* [ckeditor5-heading#t/ckeditor5-core/85](https://github.com/ckeditor/ckeditor5-heading/compare/master...t/ckeditor5-core/85)
* [ckeditor5-link#t/ckeditor5-core/85](https://github.com/ckeditor/ckeditor5-link/compare/master...t/ckeditor5-core/85)
* [ckeditor5-list#t/ckeditor5-core/85](https://github.com/ckeditor/ckeditor5-list/compare/master...t/ckeditor5-core/85)
* [ckeditor5-paragraph#t/ckeditor5-core/85](https://github.com/ckeditor/ckeditor5-paragraph/compare/master...t/ckeditor5-core/85)
* [ckeditor5-typing#t/ckeditor5-core/85](https://github.com/ckeditor/ckeditor5-typing/compare/master...t/ckeditor5-core/85)
* [ckeditor5-ui#t/ckeditor5-core/85](https://github.com/ckeditor/ckeditor5-ui/compare/master...t/ckeditor5-core/85)
* [ckeditor5-undo#t/ckeditor5-core/85](https://github.com/ckeditor/ckeditor5-undo/compare/master...t/ckeditor5-core/85)
* [ckeditor5-upload#t/ckeditor5-core/85](https://github.com/ckeditor/ckeditor5-upload/compare/master...t/ckeditor5-core/85)
* [ckeditor5-widget#t/ckeditor5-core/85](https://github.com/ckeditor/ckeditor5-widget/compare/master...t/ckeditor5-core/85)

One more thing is still missing - a warning if a user wants to load more than one plugin with the same name.

And the last thing - I guess, a part of the ticket about UI component names should be moved to another ticket.

**Comment by pomek** [comment]
One more package has been updated:

- [ckeditor5-editor-balloon-toolbar#t/ckeditor5-core/85](https://github.com/ckeditor/ckeditor5-editor-balloon-toolbar/compare/master...t/ckeditor5-core/85)

**Comment by pomek** [comment]
> One more thing is still missing - a warning if a user wants to load more than one plugin with the same name.

Ok, it's done. @Reinmar, could you look at this - https://github.com/ckeditor/ckeditor5-core/compare/t/85?expand=1 - because I'm not sure whether I'm going in the right direction.

**Comment by pomek** [comment]
The latest build on CI - https://travis-ci.org/ckeditor/ckeditor5/builds/249512375.

It contains changes with plugins' names and introduced log-warn for `PluginCollection`.

**Comment by Reinmar** [comment]
> Ok, it's done. @Reinmar, could you look at this - https://github.com/ckeditor/ckeditor5-core/compare/t/85?expand=1 - because I'm not sure whether I'm going in the right direction.

Please make a PR and we'll check.

The rest of the changes are ok.
