### ISSUE TITLE
Introduce missing deltas

### ISSUE THREAD

**Issue by pjasiun** [ckeditor/ckeditor5-core#86]
Introduce missing deltas, including:
 - move,
 - wrap,
 - unwrap,
 - rename,
 - insertText.

**Comment by scofalik** [comment]
I've pushed https://github.com/ckeditor/ckeditor5-core/tree/t/86 t/86 and introduced:
* `MoveDelta`
* `WrapDelta`
* `UnwrapDelta`
* `InsertTextDelta`
and changed `RemoveDelta`.

I'd skip `RenameDelta` (btw. I think that `SwapDelta` is a better name.. I don't like rename as it sounds HTML-y. In fact, we don't rename anything but we change the parent of some nodes. This has nothing to do with renaming). We could introduce it later if we are sure we need it for OT.
