### ISSUE TITLE
Plugin#destroy() should remove listeners

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-core#86]
The default implementation should call `this.stopListening()`.

**Comment by Reinmar** [comment]
Part of https://github.com/ckeditor/ckeditor5/issues/114.

**Comment by Reinmar** [comment]
Let's add a method `destroy()` to `PluginCollection` and `Editor.destroy()` should call this method before this:

```js
			.then( () => {
				this.document.destroy();
				this.data.destroy();
			} );
```

**Comment by Reinmar** [comment]
Also, it will be interesting to see what happens with tests after this change.

**Comment by pomek** [comment]
I added default implementation for `Plugin` class, `destroy()` method for `PluginCollection` which calls `destroy()` method on each loaded plugin and `Editor.destroy()` calls `this.plugins.destroy()` as you wanted.

[Everything works.](https://image.ibb.co/kem6Lv/maj_29_2017_09_47_53.gif)
