### ISSUE TITLE
Split OT from operations and deltas

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-core#87]
Reasoning: code size in all the use cases where you don't need the whole OT.

**Comment by pjasiun** [comment]
In fact, not counting OT, operations are created only by deltas and deltas are created only by the transaction interface, so we could bring separate set of Deltas and Operations which does not support OT. This way we will not only reduce the number of lines of code by removing transformation methods, but also removed classes we do not need if we do not provide OT: for example `ReInstert` operation and basically all classes that inherit from `Delta`.

**Comment by scofalik** [comment]
The simplest way to do so is to extract OT algorithms from operations classes into a seperate, factory class. Then, in next step, we could introduce this factory and classes mentioned by PJ (`ReinsertOperation` and deltas) in seperate module.

**Comment by scofalik** [comment]
To clear out some stuff from issues I think we can close this one for now.
OT for operations has been already moved to seperate file (`treemodel/operation/transform.js`). OT for deltas will be done in the same way.
