### ISSUE TITLE
Implement data binding between the models

### ISSUE THREAD

**Issue by oleq** [ckeditor/ckeditor5-core#93]
To make binding between features, Controllers and Views easier, Model should implement binding interface, so some part (selected attributes) of the model follows the state of another model.

With such an interface, it's quite easy to "delegate" a part of the Controller (or feature) model into View model without duplicated `on( 'change:*', ... )` listeners.

Required by #92.

**Comment by Reinmar** [comment]
R- in https://github.com/ckeditor/ckeditor5-core/pull/94#issuecomment-160646051.

**Comment by oleq** [comment]
Bravo!
