### ISSUE TITLE
Improve Position constructor validation

### ISSUE THREAD

**Issue by scofalik** [ckeditor/ckeditor5-core#96]
Improve Position constructor so it throws an error when incorrect path argument is passed. Correct path must be an instance of Array with at least one item.

**Comment by scofalik** [comment]
Pushed to branch t/96 https://github.com/ckeditor/ckeditor5-core/tree/t/96 .

**Comment by Reinmar** [comment]
Is it on review or just waiting for more love?

**Comment by scofalik** [comment]
Waiting. I'll make PR when I am ready. I'd like to make a PR only after my previous (OT) PR is on master.

**Comment by Reinmar** [comment]
#59 just landed on master.

**Comment by pjasiun** [comment]
Closed by https://github.com/ckeditor/ckeditor5-core/pull/103.
