### ISSUE TITLE
Transaction should be renamed to batch(man)

### ISSUE THREAD

**Issue by pjasiun** [ckeditor/ckeditor5-core#98]
Our transaction is simple set of changes. It has nothing in common with a transaction. In fact there will be Document.enqueue (https://github.com/ckeditor/ckeditor5-core/issues/97) mechanism which will provide something similar to transactions. We should rename `Transaction` class to something what better describe what this class do. With @Reinmar and @scofalik we agreed that `Batch` is a good then.

**Comment by pjasiun** [comment]
Of course `Batch` is a shortcut from `Batchman`.

**Comment by Reinmar** [comment]
> With @Reinmar and @scofalik we agreed that Batch is a good then.
> Of course Batch is a shortcut from Batchman.

We agreed today that we don't use shortcuts in classes names, so the class should be called Batchman.

**Comment by pjasiun** [comment]
And we could remane  `Document.createTransaction()` to simple `Document.batch()`. This method will be often used in chains so the name should be short (`doc.batch().insert( ... ).split( ... );` looks good for me).

**Comment by Reinmar** [comment]
`Document.summonBatchman()` :taxi:

**Comment by pjasiun** [comment]
Closed by https://github.com/ckeditor/ckeditor5-core/pull/103.
